spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: duke
  datasource:
    url: jdbc:h2:./assistant;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: your-openai-api-key
      model: gpt-4
