spring:
  mvc:
    static-path-pattern: /static/**
    cors:
      allowed-origins: "*"
      allow-credentials: true
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
  webflux:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all endpoints over HTTP
  endpoint:
    health:
      show-details: always  # Shows detailed health information
    shutdown:
      enabled: true  # Enables the /shutdown endpoint (use with caution)
  server:
    port: 9001  # Optional: Separate port for Actuator endpoints
    address: 127.0.0.1  # Optional: Bind to localhost for security

logging:
  level:
    org:
      springframework: DEBUG