springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chatbot-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics  # Prometheus at /actuator/prometheus
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: 9001
    address: 127.0.0.1
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c

spring.cloud.openfeign:
  micrometer:
    enabled: true

logging:
  level:
    com:
      yuce:
        chat:
          assistant: DEBUG
    org:
      springframework:
        aop: DEBUG
        security: TRACE
        jpa: TRACE
        ai.chat.client.advisor: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: basic

app:
  cors:
    allowed-origin: http://localhost:4200

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    weatherClient:
      baseConfig: default
    stockClient:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 2s
  instances:
    weatherClient:
      baseConfig: default
    stockClient:
      baseConfig: default
