spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: llama3.1:8b
          temperature: 0.3
      answer:
        options:
          model: llama3.1:8b
          temperature: 0.4
      deterministic:
        options:
          model: llama3.1:8b
          temperature: 0.0
    embedding:
      options:
        model: nomic-embed-text

  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: chat-bot
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  weather:
    client:
      url: http://localhost:8081/feign-demo/weather-client
  stock:
    client:
      url: http://localhost:8081/feign-demo/stock-client

Alpha:
  host: https://www.alphavantage.co
  api-key: ${ALPHA-API-KEY}